version: '3.8'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    container_name: web
    networks:
      - default
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "flask", "run"]
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/twitter_api_flask
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
  
  test:
    build: .
    container_name: test
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "nosetests", "-s", "--exe"]
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/twitter_api_flask
      - FLASK_ENV=test

volumes:
  postgres_data: